name: Deploy Environments

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-development:
    needs: docker-ci
    uses: ./.github/workflows/deploy-to-kind.yml
    with:
      environment: development

  deploy-staging:
    needs: docker-ci
    uses: ./.github/workflows/deploy-to-kind.yml
    with:
      environment: staging
